name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - ".git**"
  pull_request:

jobs:
  lint-scss:
    name: Lint SCSS
    uses: publishing-platform/publishing-platform-infrastructure/.github/workflows/stylelint.yml@main
    with:
      files: "app/assets/stylesheets/"

  lint-javascript:
    name: Lint JavaScript
    uses: publishing-platform/publishing-platform-infrastructure/.github/workflows/standardx.yml@main
    with:
      files: "'app/javascript/**/*.js'"

  lint-ruby:
    name: Lint Ruby
    uses: publishing-platform/publishing-platform-infrastructure/.github/workflows/rubocop.yml@main

  test-ruby:
    name: Test Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    

      - name: Checkout Publishing API (for Content Schemas)
        uses: actions/checkout@v4
        with:
          repository: publishing-platform/publishing-api
          ref: main
          path: vendor/publishing-api      
          token: ${{ secrets.PUBLISHING_PLATFORM_CI_GITHUB_API_TOKEN }}      

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: publishing-platform/publishing-platform-infrastructure/.github/actions/setup-node@main

      - name: Precompile assets
        uses: publishing-platform/publishing-platform-infrastructure/.github/actions/precompile-rails-assets@main

      - name: Run RSpec
        env:
          RAILS_ENV: test
          PUBLISHING_PLATFORM_CONTENT_SCHEMAS_PATH: vendor/publishing-api/content_schemas
        run: bundle exec rake spec           
